import mongoose from 'mongoose';

const studentSchema = new mongoose.Schema({

    email:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    teacher:{
        type:String,
        required:true
    }, 
    Race:{
        type:String,
        required:true
    },
    school:{
        tye:String,
        required:false
    },
    sex:{
        type:String,
        required:true
    },
    age:{
        type:String,
        required:true
    },
    address:{
        type:String,
        required:false
    },
    famsize:{
        type:String,
        required:true
    },
    Pstatus:{
        type:String,
        required:false
    },
    Medu:{
        type:String,
        required:true
    },
    Fedu:{
        type:String,
        required:true
    },
    Mjob:{
        type:String,
        required:true
    },
    Fjob:{
        type:String,
        required:true
    },
    reason:{
        type:String,
        required:true
    },
    guardian:{
        type:String,
        required:true
    },
    traveltime:{
        type:String,
        required:true
    },
    studytime:{
        type:String,
        required:true
    },
    failures:{
        type:String,
        required:true
    },
    schoolsup:{
        type:String,
        required:true
    },
    famsup:{
        type:String,
        required:true
    },
    paid:{
        type:String,
        required:true
    },
    activities:{
        type:String,
        required:true
    },
    nursery:{
        type:String,
        required:true
    },
    higher:{
        type:String,
        required:true
    },
    internet:{
        type:String,
        required:true
    },
    romantic:{
        type:String,
        required:true
    },
    famrel:{
        type:String,
        required:true
    },
    freetime:{
        type:String,
        required:true
    },
    goout:{
        type:String,
        required:true
    },
    Dalc:{
        type:String,
        required:true
    },
    Walc:{
        type:String,
        required:true
    },
    health:{
        type:String,
        required:true
    },
    absences:{
        type:String,
        required:true
    },
    G1:{
        type:String,
        required:true
    },
    G2:{
        type:String,
        required:true
    },
    G3:{
        type:String,
        required:true
}

});


let students = mongoose.models.student || mongoose.model('student', studentSchema);

export default students;