import mongoose from 'mongoose';

const studentSchema = new mongoose.Schema({

    email:{
        type:String,
        required:true
    },
    name:{
        type:String,
        required:true
    },
    teacher:{
        type:String,
        required:true
    },  
    race:{
        type:String,
        required:true
    },
    age:{
        type:Number,
        required:true
    },
    famSize:{
        type:Number,
        required:true
    },
    Fedu:{
        type:Number,
        required:true
    },
    reason:{
        type:number,
        required:true
    },
    guardian:{
        type:Number,
        required:true
    },
    traveltime:{
        type:Number,
        required:true
    },
    studytime:{
        type:Number,
        required:true
    },
    failures:{
        type:Number,
        required:true
    },
    famrel:{
        type:Number,
        required:true
    },
    freetime:{
        type:Number,
        required:true
    },
    Walc:{
        type:Number,
        required:true
    },
    health:{
        type:Number,
        required:true
    },
    G1:{
        type:Number,
        required:true
    },
    G2:{
        type:Number,
        required:true
    },
    gender:{
        type:Number,
        required:true
    },
    absences:{
        type:Number,
        required:true
    },
    address:{
        type:Number,
        required:true
    },
    schoolsup:{
        type:Number,
        required:true
    },
    famsup:{
        type:Number,
        required:true
    },
    paid:{
        type:Number,
        required:true
    },
    activities:{
        type:Number,
        required:true
    },
    nursery:{
        type:Number,
        required:true
    },
    higher:{
        type:Number,
        required:true
    },
    internet:{
        type:Number,
        required:true
    },
    romantic:{
        type:Number,
        required:true
    }

});


let student= mongoose.model.student || mongoose.model('student', studentSchema);
export default student;